namespace Reactive.Multi.Agent.MCP.Core.Models;

/// <summary>
/// Represents the action plan generated by a supervisor for a specific session, including the sequence of actions,
/// automatically applied actions, and next runnable tasks.
/// </summary>
/// <remarks>This class is typically used to convey the results of a supervisor's evaluation process, providing
/// details about which actions should be taken, their order, and which tasks are eligible to run next. All collections
/// are read-only to ensure the integrity of the action plan data.</remarks>
public sealed class SupervisorActionPlan
{
    public string SessionId { get; set; } = string.Empty;

    public DateTimeOffset EvaluatedAtUtc { get; set; }

    public IReadOnlyList<string> OrderedActions { get; set; } = [];

    public IReadOnlyList<string> AutoAppliedActions { get; set; } = [];

    public IReadOnlyList<NextTaskCandidate> NextRunnableTasks { get; set; } = [];

    public IReadOnlyList<string> ActionIds { get; set; } = [];
}
